# Generated by Django 5.2.5 on 2025-09-24 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_rename_category_id_product_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.TextField(null=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('middle_name', models.TextField()),
                ('tracking_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Очікує підтвердження'), ('CONFIRMED', 'Підтверджене'), ('PROCESSING', 'Обробляється'), ('SHIPPED', 'Відправлено'), ('DELIVERED', 'Доставлено'), ('CANCELED', 'Скасоване'), ('RETURNED', 'Повернення')], default='PENDING', max_length=15)),
                ('total_price', models.PositiveIntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('payment_method', models.CharField(choices=[('CASH_ON_DELIVERY', 'Готівка при отриманні'), ('CARD_ONLINE', 'Банківська карта онлайн'), ('CARD_ON_DELIVERY', 'Карта при отриманні')], default='CASH_ON_DELIVERY', max_length=30)),
                ('shipping_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
