# Generated by Django 5.2.5 on 2025-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_cart_id_remove_cartitem_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='session_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
